# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fb11a89d0b583a9ba76a70be71a1d7b6"
name = "App-Banao"
handle = "app-banao"
application_url = "https://newspaper-residence-transcription-alive.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_draft_orders,write_draft_orders,read_orders,write_orders,read_customers,write_customers"

[auth]
redirect_urls = ["https://newspaper-residence-transcription-alive.trycloudflare.com/auth/callback", "https://newspaper-residence-transcription-alive.trycloudflare.com/auth/shopify/callback", "https://newspaper-residence-transcription-alive.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
